spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          filters:
            - AuthenticationFilter
            - APIResponseTransformFilter
            - RewritePath=/api/user/(?<segment>.*), /$\{segment}

          predicates:
            - Path=/api/user/**

        - id: subscription-service
          uri: lb://subscription-service
          filters:
            - AuthenticationFilter
            - APIResponseTransformFilter
            - RewritePath=/api/subscriptions/(?<segment>.*),/$\{segment}
          predicates:
            - Path=/api/subscriptions/**

server:
  port: ${API_GATEWAY_PORT:8005}
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}"
    register-with-eureka: true
